application:
  name: simple-example-jhipster-with-postgresql
  project: simple-example-jhipster-with-postgresql
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: my-db
routers:
  - name: main
    routes:
      - application_name: simple-example-jhipster-with-postgresql
        paths:
          - /
